import { Component, ErrorInfo, ReactNode, useEffect, useMemo, useState } from 'react';

type AnyRecord = Record<string, any>;
const API = import.meta.env.VITE_API_URL || '/api/v1';
const backendUrl = import.meta.env.VITE_API_URL || 'http://127.0.0.1:8000/api/v1';

async function call(path: string, init?: RequestInit) {
  const response = await fetch(`${API}${path}`, { headers: { 'content-type': 'application/json' }, ...init });
  const data = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(data.error?.message || `Request failed (${response.status})`);
  return data;
}

function download(name: string, content: string, type = 'application/json') {
  const url = URL.createObjectURL(new Blob([content], { type }));
  const link = document.createElement('a'); link.href = url; link.download = name; link.click(); URL.revokeObjectURL(url);
}

class AppErrorBoundary extends Component<{ children: ReactNode }, { error: Error | null }> {
  state = { error: null as Error | null };
  static getDerivedStateFromError(error: Error) { return { error }; }
  componentDidCatch(error: Error, info: ErrorInfo) { console.error('Workbench render error', error, info); }
  render() { return this.state.error ? <Unavailable title="Workbench unavailable" detail="The interface could not render this view." retry={() => this.setState({ error: null })} /> : this.props.children; }
}

function Unavailable({ title = 'Backend unavailable', detail, retry }: { title?: string; detail: string; retry: () => void }) {
  return <main className="unavailable"><span className="eyebrow">ARMIE AI LABS · v0.3.0</span><h1>{title}</h1><p>{detail}</p><p>Configured backend: <code>{backendUrl}</code></p><p>Start it from the repository root with:</p><code className="command">make workbench</code><button className="primary" onClick={retry}>Retry connection</button></main>;
}

function ScoreStack({ item }: { item: AnyRecord }) {
  return <details className="score-stack"><summary>{item.score?.toFixed?.(4) ?? 'Not available'} · {item.score_type}</summary><p className="muted">Source: {item.score_source || 'Not available'}</p>{Object.entries(item.score_stack || {}).map(([key, value]) => <div className="score-row" key={key}><span>{key}</span><b>{value === null || value === undefined ? 'Not available' : typeof value === 'number' ? value.toFixed(4) : String(value)}</b></div>)}<small>Scores are provider-specific and are not directly comparable across profiles.</small></details>;
}

function ExecutionContext({ context }: { context: AnyRecord }) { return <div className="metrics">{Object.entries(context || {}).map(([section, values]) => <div className="metric" key={section}><span>{section}</span><b>{Object.entries((values || {}) as AnyRecord).map(([key, value]) => `${key}: ${value === null || value === undefined ? 'Not applicable' : Array.isArray(value) ? value.join(', ') || 'Not applicable' : String(value)}`).join(' · ')}</b></div>)}</div>; }

function Audit({ stages }: { stages: AnyRecord[] }) {
  return <div className="audit-list">{stages.map(stage => <details className="audit-stage" key={stage.stage}><summary><span>{stage.stage}</span><em className={`stage-${stage.status}`}>{stage.status}</em><small>{stage.summary?.provider || ''} · {stage.summary?.latency_ms?.toFixed?.(2) || 0} ms · in {stage.summary?.input_count ?? '—'} · out {stage.summary?.output_count ?? '—'}</small></summary><div className="stage-fields">{Object.entries(stage.summary || {}).filter(([key]) => !['candidates', 'warnings'].includes(key)).map(([key, value]) => <div className="comparison-row" key={key}><span>{key.replaceAll('_', ' ')}</span><b>{typeof value === 'object' ? JSON.stringify(value) : String(value ?? '—')}</b></div>)}</div><details><summary>Raw stage detail</summary><pre>{JSON.stringify(stage.summary, null, 2)}</pre></details></details>)}</div>;
}

function WorkbenchView({ onQueryLab }: { onQueryLab: () => void }) {
  const [query, setQuery] = useState('Find healthcare experts with Azure AI experience');
  const [profile, setProfile] = useState('baseline'); const [session, setSession] = useState<string>(); const [response, setResponse] = useState<AnyRecord>(); const [selected, setSelected] = useState<string>(); const [panel, setPanel] = useState('audit'); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  const run = async () => { setLoading(true); setError(''); try { const data = await call('/query', { method: 'POST', body: JSON.stringify({ query, profile, session_id: session }) }); setResponse(data); setSession(data.session_id); setSelected(data.results?.[0]?.id); } catch (e) { console.error('Workbench query failed', e); setError((e as Error).message); } finally { setLoading(false); } };
  const trace = response?.raw_trace;
  return <>
    <header><div><span className="eyebrow">ARMIE AI LABS · v0.3.0</span><h1>Retrieval Workbench</h1><p>Inspect how a query becomes evidence, ranking, and a verified answer.</p></div><div className="header-actions"><button onClick={onQueryLab}>Query Lab</button><button onClick={async () => { const s = await call('/sessions', { method: 'POST' }); setSession(s.session_id); setResponse(undefined); }}>New session</button></div></header>
    <section className="querybar"><textarea value={query} onChange={e => setQuery(e.target.value)} /><select value={profile} onChange={e => setProfile(e.target.value)}><option value="baseline">Baseline</option><option value="model-enhanced">Model-enhanced</option></select><button className="primary" onClick={run} disabled={loading}>{loading ? 'Running…' : 'Run retrieval'}</button></section>{error && <div className="error">{error}</div>}
    <div className="grid"><section className="panel"><h2>Answer Summary</h2><p>{response?.answer_summary?.text || 'Run a query to see the deterministic evidence summary.'}</p>{response && <><p className="muted">Planner: {response.execution_context?.planner?.actual_provider} · Reranker: {response.execution_context?.reranker?.actual_provider || 'none'}</p><h2>Results</h2>{response.results.map((item: AnyRecord) => <article className={`result ${selected === item.id ? 'selected' : ''}`} key={item.id} onClick={() => { setSelected(item.id); setPanel('evidence'); }}><div><b>#{item.rank} {item.title}</b><ScoreStack item={item} /></div><p>{item.content}</p><small>{Object.entries(item.metadata).slice(0, 3).map(([k, v]) => `${k}: ${v}`).join(' · ')}</small></article>)}</>}</section>
      <section className="panel"><div className="tabs">{['audit', 'evidence', 'verification', 'trace'].map(tab => <button className={panel === tab ? 'active' : ''} onClick={() => setPanel(tab)} key={tab}>{tab === 'trace' ? 'Raw Trace' : tab[0].toUpperCase() + tab.slice(1)}</button>)}</div>{panel === 'audit' && <>{response ? <Audit stages={response.stage_summaries} /> : <p className="muted">Planner, retrievers, processors, verification, and evaluation stages will appear here.</p>}</>}{panel === 'evidence' && <Evidence response={response} selected={selected} />}{panel === 'verification' && <Verification response={response} />}{panel === 'trace' && response && <div><button onClick={() => navigator.clipboard?.writeText(response.trace_id)}>Copy Trace ID</button> <button onClick={() => navigator.clipboard?.writeText(JSON.stringify(response.plan, null, 2))}>Copy Plan JSON</button> <button onClick={() => download(`retrieval-trace-${response.trace_id}.json`, JSON.stringify(trace, null, 2))}>Download Trace JSON</button> <button onClick={() => download(`execution-report-${response.trace_id}.json`, JSON.stringify(response, null, 2))}>Download Execution Report</button><pre className="trace-json">{JSON.stringify(trace, null, 2)}</pre></div>}</section>
      <section className="panel"><h2>Metrics</h2>{response ? <Metrics metrics={response.metrics} /> : <p className="muted">Metrics appear after execution.</p>}<h2>Execution Context</h2>{response ? <ExecutionContext context={response.execution_context} /> : <p className="muted">Execution context appears after execution.</p>}</section></div></>;
}

function Evidence({ response, selected, compact = false }: { response?: AnyRecord; selected?: string; compact?: boolean }) { const detail = response?.evidence_by_result?.[selected || '']; const selectedItem = response?.results?.find((item: AnyRecord) => item.id === selected); if (!detail) return <p className="muted">Select a result to inspect why it was returned.</p>; return <div className={compact ? 'compact-evidence' : ''}><h3>Selected result: {selectedItem?.id || selected} · {selectedItem?.title || 'Unknown result'}</h3><p className="muted">Evidence is projected from the retrieval trace; biographies remain in Results.</p>{Object.entries(detail).map(([stage, value]) => <details key={stage}><summary>{stage}</summary><pre>{JSON.stringify(value, null, 2)}</pre></details>)}</div>; }
function Verification({ response }: { response?: AnyRecord }) { if (!response) return <p className="muted">Verification appears after execution.</p>; const findings = response.verification.findings || []; return <div><div className={`status ${response.verification.status === 'passed' ? 'ok' : ''}`}>{response.verification.status}</div>{findings.length ? findings.map((finding: AnyRecord) => <details className="finding" key={finding.rule_id}><summary>{finding.rule_id} · {finding.name} · {finding.status}</summary><p>{finding.description}</p><small>Expected: {finding.expected} · Actual: {finding.actual}</small><p>Results: {finding.related_result_ids?.join(', ') || 'none'}<br />Evidence: {finding.related_evidence_ids?.join(', ') || 'none'}</p></details>) : <p className="error">Verification summary is available, but detailed findings were not returned.</p>}</div>; }
function Metrics({ metrics }: { metrics: AnyRecord }) { const countField = (key: string) => /count|top_k/.test(key); return <div className="metrics">{Object.entries(metrics).map(([key, value]) => <div className="metric" key={key}><span>{key.replaceAll('_', ' ')}</span><b>{value === null || value === undefined ? 'Not available' : typeof value === 'number' ? `${countField(key) ? Math.round(value) : value.toFixed(2)}${key.includes('latency') ? ' ms' : ''}` : typeof value === 'string' ? value : JSON.stringify(value)}</b></div>)}{metrics.quality_status === 'unlabelled' && <p className="muted metric-note">Quality metrics unavailable — no Ground Truth label exists for this query.</p>}</div>; }

function Comparison({ compare }: { compare: AnyRecord }) {
  const left = compare.left || {}; const right = compare.right || {}; const overlap = compare.overlap || {};
  const planner = (side: AnyRecord) => side.planner || {}; const reranker = (side: AnyRecord) => side.reranker || {};
  const field = (value: unknown) => value === undefined || value === null || value === '' ? '—' : String(value);
  const latency = (value: unknown) => typeof value === 'number' ? value >= 1000 ? `${(value / 1000).toFixed(2)} s` : `${value.toFixed(2)} ms` : 'Not available';
  const rows = [['Profile', left.profile, right.profile], ['Planner', planner(left).actual, planner(right).actual], ['Planner model', planner(left).model || 'Not applicable', planner(right).model || 'Not applicable'], ['Strategy', planner(left).strategy, planner(right).strategy], ['Retriever set', (planner(left).retrievers || []).join(', ') || '—', (planner(right).retrievers || []).join(', ') || '—'], ['Reranker', reranker(left).actual || 'Not applicable', reranker(right).actual || 'Not applicable'], ['Fallback', (left.fallbacks || []).join('; ') || 'none', (right.fallbacks || []).join('; ') || 'none'], ['Total latency', latency(left.metrics?.total_latency_ms), latency(right.metrics?.total_latency_ms)]];
  return <div className="comparison"><p className="muted">{compare.interpretation}</p><div className="comparison-grid"><div><h3>Left run</h3>{rows.map(row => <div className="comparison-row" key={`l-${row[0]}`}><span>{row[0]}</span><b>{field(row[1])}</b></div>)}</div><div><h3>Right run</h3>{rows.map(row => <div className="comparison-row" key={`r-${row[0]}`}><span>{row[0]}</span><b>{field(row[2])}</b></div>)}</div></div><h3>Overlap and ranking</h3><div className="metrics"><div className="metric"><span>Common results</span><b>{field(overlap.common_count)}</b></div><div className="metric"><span>Jaccard overlap</span><b>{typeof overlap.jaccard === 'number' ? overlap.jaccard.toFixed(3) : '—'}</b></div><div className="metric"><span>Latency delta</span><b>{typeof compare.latency_delta_ms === 'number' ? `${compare.latency_delta_ms >= 1000 ? `+${(compare.latency_delta_ms / 1000).toFixed(2)} s` : `${compare.latency_delta_ms >= 0 ? '+' : ''}${compare.latency_delta_ms.toFixed(2)} ms`}` : 'Not available'}</b></div></div><details><summary>Rank movement</summary><div className="rank-table">{(compare.rank_delta || []).map((item: AnyRecord) => <div className="comparison-row" key={item.id}><span>{item.id}</span><b>{field(item.left_rank)} → {field(item.right_rank)}</b></div>)}</div></details><details><summary>Raw comparison JSON</summary><pre>{JSON.stringify(compare, null, 2)}</pre></details></div>;
}

function QueryLab({ onBack }: { onBack: () => void }) { const [cases, setCases] = useState<AnyRecord[]>([]); const [selected, setSelected] = useState<AnyRecord>(); const [profile, setProfile] = useState('baseline'); const [repeat, setRepeat] = useState(1); const [runs, setRuns] = useState<AnyRecord[]>([]); const [compare, setCompare] = useState<AnyRecord>(); const [error, setError] = useState(''); useEffect(() => { call('/query-lab/cases').then(data => { setCases(data.cases); setSelected(data.cases[0]); }).catch(e => setError(e.message)); }, []); const execute = async () => { if (!selected) return; try { const completed: AnyRecord[] = []; for (let i = 0; i < Math.min(repeat, 5); i += 1) completed.push(await call('/query-lab/runs', { method: 'POST', body: JSON.stringify({ case_id: selected.id, profile }) })); setRuns(previous => [...completed, ...previous]); } catch (e) { setError((e as Error).message); } }; const doCompare = async () => { if (runs.length < 2) return; setCompare(await call('/query-lab/compare', { method: 'POST', body: JSON.stringify({ left_run_id: runs[1].run_id, right_run_id: runs[0].run_id }) })); }; return <main><header><div><span className="eyebrow">ARMIE AI LABS · QUERY LAB</span><h1>Benchmark and compare</h1><p>Run labelled cases and inspect repeatability without a load test.</p></div><button onClick={onBack}>Workbench</button></header>{error && <div className="error">{error}</div>}<div className="lab-grid"><section className="panel"><h2>Case Library</h2>{cases.map(item => <button className={`case ${selected?.id === item.id ? 'active' : ''}`} onClick={() => setSelected(item)} key={item.id}><b>{item.name}</b><small>{item.id} · {item.labelled ? 'labelled' : 'unlabelled'}</small><span>{item.query}</span></button>)}</section><section className="panel">{selected ? <><h2>{selected.name}</h2><p>{selected.query}</p><p className="muted">Category: {selected.category} · Purpose: {selected.purpose}</p><pre>{JSON.stringify({ expected_constraints: selected.expected_constraints, acceptable_strategies: selected.acceptable_strategies, relevant_ids: selected.relevant_ids }, null, 2)}</pre><select value={profile} onChange={e => setProfile(e.target.value)}><option>baseline</option><option>model-enhanced</option></select><input aria-label="repeat count" type="number" min="1" max="5" value={repeat} onChange={e => setRepeat(Number(e.target.value))} /><button className="primary" onClick={execute}>Execute case</button></> : <p>Select a case.</p>}<h2>Run History</h2>{runs.map(run => <div className="run" key={run.run_id}><b>{run.profile}</b> · {run.run_id.slice(0, 8)} · {run.verification.status}<span>{run.results?.map((x: AnyRecord) => x.id).join(', ')}</span></div>)}{runs.length > 1 && <button onClick={doCompare}>Compare latest two</button>}{compare && <Comparison compare={compare} />}</section></div></main>; }

function WorkbenchApp() { const [view, setView] = useState<'workbench' | 'lab'>('workbench'); const [backendReady, setBackendReady] = useState<boolean | null>(null); const [error, setError] = useState(''); const check = async () => { try { await call('/health'); await call('/capabilities'); setBackendReady(true); } catch (e) { console.error('Workbench backend check failed', e); setBackendReady(false); setError((e as Error).message); } }; useEffect(() => { check(); }, []); if (backendReady === false) return <Unavailable detail={error || 'The API health or capabilities endpoint did not respond.'} retry={check} />; return <><nav className="top-nav"><button className={view === 'workbench' ? 'active' : ''} onClick={() => setView('workbench')}>Workbench</button><button className={view === 'lab' ? 'active' : ''} onClick={() => setView('lab')}>Query Lab</button></nav>{view === 'workbench' ? <WorkbenchView onQueryLab={() => setView('lab')} /> : <QueryLab onBack={() => setView('workbench')} />}</>; }
export default function App() { return <AppErrorBoundary><WorkbenchApp /></AppErrorBoundary>; }
